### ISSUE TITLE
Security Flaw

### ISSUE THREAD

**Issue by nmccann** [m1entus/MZAppearance#2]
Hi,

Our static scan tool reported `MZAppearance` as having a security flaw in `NSInvocation+Copy.m` on [this line](https://github.com/m1entus/MZAppearance/blob/master/MZAppearance/NSInvocation%2BCopy.m#L30). Evidently it expects the return value of `malloc()` to be checked or `NULL`. 

I had intended to create a pull request for this, but am unsure what should be returned in the case that `malloc()` fails. The two options I see are: return `NULL` and update all the places that call `jbb_removeObjCTypeQualifiers()` to check for `NULL` (and then update all of them to return some value on failure), or just return `aType`. Obviously returning and checking for `NULL` would be ideal, since just return `aType` could put the code into an unknown state as it doesn't know that the `malloc()` failed. The issue with returning `NULL` is that it affects many other methods.

What would you suggest?

Thank you!

**Comment by zhangsiyuan** [comment]
Thanks!
