### ISSUE TITLE
New release with Carthage support

### ISSUE THREAD

**Issue by KHellkvist** [m1entus/MZAppearance#8]
Would be nice to have a new release of this with carthage support included

**Comment by m1entus** [comment]
PR appriciated bc i am not using carthage in any of my projects

**Comment by KHellkvist** [comment]
https://github.com/m1entus/MZFormSheetPresentationController/pull/66
Opened this pull request for MZForm......
Your master branch have Carthage support already but the latest "release" version under GitHub does not.

**Comment by m1entus** [comment]
Okay thanks, merged
